### ISSUE TITLE
[Enhancement] Put expert_ids in GPU

### ISSUE THREAD

**Issue by hogura99** [USC-NSL/DisagMoE#1]
* `expert_ids` is used in Dispatcher; ExpertEngine; AttnEngine
* Notice that ExpertEngine & AttnEngine may incur 2 CPU->GPU sync
* If we put the `expert_ids` in CPU, then we only have 1 GPU->CPU sync in Dispatcher
* Bonus: fuse the batch selection & permute operator in ExpertEngine.

**Comment by shawlleyw** [comment]
This will not have a significant impact as the copy is very fast.
